# Generated by Django 5.1.4 on 2025-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resttbl',
            name='location',
        ),
        migrations.AddField(
            model_name='resttbl',
            name='lattitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resttbl',
            name='logitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
