# Generated by Django 5.1.4 on 2025-01-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resttbl_location_resttbl_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktbl',
            name='date',
            field=models.DateField(),
        ),
    ]
