# Generated by Django 5.1.4 on 2025-01-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_feedbacktbl_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtbl',
            name='type',
            field=models.CharField(default='Happy', max_length=20),
            preserve_default=False,
        ),
    ]
