# Generated by Django 3.2.25 on 2025-01-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_songtbl_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktbl',
            name='ebooklink',
            field=models.CharField(max_length=500),
        ),
    ]
