# Generated by Django 3.2.25 on 2025-01-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booktbl_ebooklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booktbl')),
            ],
        ),
    ]
